name: code-style

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: ['22.x']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install NPM Dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
